### ISSUE TITLE
Python3, Python2, or Both

### ISSUE THREAD

**Issue by falakmasir** [EducationalTestingService/rstfinder#44]
Hi --

Thanks for making this library publicly available. I was wondering if this library only works with Python 3 or parts of it requires Python 2. Some of the files have #!/usr/bin/env python3 line on top but some of them do not. For example, parse_util.py does not have the line on top but uses the Python 3 syntax to import xmlrpc.client. 

Should I use pip3 to install the package?

Best,

**Comment by desilinguist** [comment]
It should work with Python 3. Please try it and update the issue if it
doesn't.

**Comment by desilinguist** [comment]
Since there was no further activity, I'll assume the issue was resolved.
