### ISSUE TITLE
update to latest version of skll

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/rstfinder#47]

**Comment by ghost** [comment]
Isn't it that #46 will automatically use SKLL latest version.

**Comment by desilinguist** [comment]
We have already updated to SKLL v2.0 in #54 but that's not the _latest_ version. Do we just stop there @aoifecahill @bndgyawali ?

**Comment by aoifecahill** [comment]
I would rather unpin the dependency or at least switch to minimum only. Setting an exact version will be a pain for downstream apps at some point in the future.

**Comment by desilinguist** [comment]
Yeah, I think unpinning makes a lot of sense. So that way it will work internally at ETS too where the SKLL version may be pinned in another place.
