### ISSUE TITLE
How to get the corpora？

### ISSUE THREAD

**Issue by zhongluwang** [EducationalTestingService/rstfinder#49]
How to get ~/corpora/rst_discourse_treebank?

**Comment by aoifecahill** [comment]
It's available through the LDC: https://catalog.ldc.upenn.edu/ldc2002t07

**Comment by Syauri** [comment]
This link does not work anymore.

**Comment by desilinguist** [comment]
Looks like the ID just needs to be uppercase and then it works fine:  https://catalog.ldc.upenn.edu/LDC2002T07

**Comment by kaushal18** [comment]
Do I need to pay to download the corpora?

**Comment by desilinguist** [comment]
You or the organization you belong to (university, employer) need to be a member of the LDC to get the corpus. See more details [here](https://www.ldc.upenn.edu/members/join-ldc).
